server:
  port: 8080
  # 本项目必须以 / 结束或者不填默认 /
  contextPath: "/api/print/" # solon v1.11.2 后支持（或者 "!/test-service/" 表示原路径不能再请求 v2.6.3 后支持）

solon.app:
  name: 'iboot-print'
  group: 'iboot'

solon.logging:
  appender:
    console:
      pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %magenta(${PID:-}) --- %-15([%15.15thread]) %-56(%cyan(%-40.40logger{39}%L)) : %msg%n"
      level: INFO
    file:
      pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level ${PID:-} --- %-15([%15.15thread]) %-56(%-40.40logger{39}%L) : %msg%n"
      level: INFO